(cl:defpackage tortoisebot_waypoints-msg
  (:use )
  (:export
   "<WAYPOINTACTIONACTION>"
   "WAYPOINTACTIONACTION"
   "<WAYPOINTACTIONACTIONFEEDBACK>"
   "WAYPOINTACTIONACTIONFEEDBACK"
   "<WAYPOINTACTIONACTIONGOAL>"
   "WAYPOINTACTIONACTIONGOAL"
   "<WAYPOINTACTIONACTIONRESULT>"
   "WAYPOINTACTIONACTIONRESULT"
   "<WAYPOINTACTIONFEEDBACK>"
   "WAYPOINTACTIONFEEDBACK"
   "<WAYPOINTACTIONGOAL>"
   "WAYPOINTACTIONGOAL"
   "<WAYPOINTACTIONRESULT>"
   "WAYPOINTACTIONRESULT"
  ))

