; Auto-generated. Do not edit!


(cl:in-package tortoisebot_waypoints-msg)


;//! \htmlinclude WaypointActionResult.msg.html

(cl:defclass <WaypointActionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass WaypointActionResult (<WaypointActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaypointActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaypointActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tortoisebot_waypoints-msg:<WaypointActionResult> is deprecated: use tortoisebot_waypoints-msg:WaypointActionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <WaypointActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tortoisebot_waypoints-msg:success-val is deprecated.  Use tortoisebot_waypoints-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaypointActionResult>) ostream)
  "Serializes a message object of type '<WaypointActionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaypointActionResult>) istream)
  "Deserializes a message object of type '<WaypointActionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaypointActionResult>)))
  "Returns string type for a message object of type '<WaypointActionResult>"
  "tortoisebot_waypoints/WaypointActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaypointActionResult)))
  "Returns string type for a message object of type 'WaypointActionResult"
  "tortoisebot_waypoints/WaypointActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaypointActionResult>)))
  "Returns md5sum for a message object of type '<WaypointActionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaypointActionResult)))
  "Returns md5sum for a message object of type 'WaypointActionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaypointActionResult>)))
  "Returns full string definition for message of type '<WaypointActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaypointActionResult)))
  "Returns full string definition for message of type 'WaypointActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaypointActionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaypointActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'WaypointActionResult
    (cl:cons ':success (success msg))
))
