version: '3.7'

services:
  # ROS Master running roscore
  master:
    image: osrf/ros:noetic-desktop-full
    container_name: ros1_master
    ports:
      - "11311:11311" # Expose roscore to the host (optional)
    networks:
      - rosnet
    command: /bin/bash -c "source /opt/ros/noetic/setup.bash && roscore"

  # Gazebo container
  gazebo:
    image: eldgar/tortoisebot-ros1-gazebo
    container_name: tortoisebot-ros1-gazebo
    depends_on:
      - master
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://master:11311
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Enable GUI display for Gazebo
    command: >
      /bin/bash -c "source /opt/ros/noetic/setup.bash &&
                    source /simulation_ws/devel/setup.bash &&
                    roslaunch tortoisebot_gazebo tortoisebot_playground.launch"

  # Waypoints container
  waypoints:
    image: eldgar/tortoisebot-ros1-waypoints
    container_name: tortoisebot-ros1-waypoints
    depends_on:
      - master
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://master:11311
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: >
      /bin/bash -c "source /opt/ros/noetic/setup.bash &&
                    source /simulation_ws/devel/setup.bash &&
                    rosrun course_web_dev_ros tortoisebot_action_server.py"

networks:
  rosnet:
    driver: bridge
