version: '3.7'

services:
  # ROS Master running roscore
  master:
    image: osrf/ros:noetic-desktop-full
    container_name: ros1_master
    ports:
      - "11311:11311"  # Expose roscore to the host (optional)
    networks:
      - rosnet
    command: >
      bash -c "source /opt/ros/noetic/setup.bash &&
               roscore"

  # Gazebo container
  gazebo:
    image: eldgar/tortoisebot-ros1-gazebo-test  # Ensure you use the updated image
    container_name: tortoisebot-ros1-gazebo
    depends_on:
      - waypoints
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://master:11311
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Enable GUI display for Gazebo
    command: >
      bash -c "source /opt/ros/noetic/setup.bash &&
               source devel/setup.bash &&
               roslaunch tortoisebot_gazebo tortoisebot_playground.launch &&
               rostest tortoisebot_waypoints waypoints_test.test --reuse-master"

  # Waypoints container
  waypoints:
    image: eldgar/tortoisebot-ros1-gazebo-test
    container_name: tortoisebot-ros1-waypoints
    depends_on:
      - master
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://master:11311
    command: >
      bash -c "source /opt/ros/noetic/setup.bash &&
               source devel/setup.bash &&
               rosrun tortoisebot_waypoints tortoisebot_action_server.py"

  # test:
  #   image: eldgar/tortoisebot-ros1-gazebo-test
  #   container_name: tortoisebot-ros1-test
  #   depends_on:
  #     - waypoints
  #   networks:
  #     - rosnet
  #   environment:
  #     - ROS_MASTER_URI=http://master:11311
  #   command: >
  #     bash -c "source /opt/ros/noetic/setup.bash &&
  #              source /simulation_ws/devel/setup.bash &&
  #              rostest tortoisebot_waypoints waypoints_test.test --reuse-master"

networks:
  rosnet:
    driver: bridge

